### ISSUE TITLE
Failed to execute script 'gui' due to unhandled exception

### ISSUE THREAD

**Issue by Kamii-Sam** [effusiveperiscope/StyleTTS2_GUI#1]
When I try to open the program, I get this error...

177
Traceback (most recent call last):
  File "gui.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "core.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "g2p_utils.py", line 73, in <module>
  File "g2p_utils.py", line 64, in load_dictionary
UnicodeDecodeError: 'cp932' codec can't decode byte 0x89 in position 5953: illegal multibyte sequence
[15260] Failed to execute script 'gui' due to unhandled `exception!

What do I do? I'm using Windows 11, by the way.

**Comment by effusiveperiscope** [comment]
Should be fixed in 5b9e1ef Try new release
